Added default files to image, changed certificate extenstions to der.

diff --git a/get-ms-certs b/get-ms-certs
--- a/get-ms-certs
+++ b/get-ms-certs
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 
@@ -12,9 +12,9 @@ get_file() {
 
 	tmpfile="$(mktemp)"
 	if ! curl --fail -L $2 -o $tmpfile >/dev/null 2>&1 ; then
-		echo "Error: Unable to retrieve link: $2"
+		echo "Warning: Unable to retrieve file: $(basename $4)."
 		rm -f $tmpfile
-		exit 1
+		return
 	fi
 
 	if diff -s $tmpfile $4 >/dev/null 2>&1 ; then
@@ -29,71 +29,78 @@ get_file() {
 
 sbsiglist_if_changed() {
 
-	if [ "$changed" == "true" ]; then
-		echo sbsiglist --type x509 --owner "$4" $5 --output $7
+	if [ "$changed" = "true" ]; then
+		echo sbsiglist $*
+		sbsiglist $* || echo "failed"
 	fi
 }
 
 # Get the Microsoft Corporation KEK CA 2011 certificate.
 
+# Copy default files, then update if changed.
+if [ $(($(ls -l $ms | wc -l))) -lt 2 ]; then
+	echo "Copying default certificates."
+	cp --preserve=timestamps /root/ms/* $ms/.
+fi
+
 changed=
-get_file -L https://go.microsoft.com/fwlink/p/?linkid=321185 -o $ms/MicCorKEKCA2011_2011-06-24.crt
+get_file -L https://go.microsoft.com/fwlink/p/?linkid=321185 -o $ms/MicCorKEKCA2011_2011-06-24.der
 
 # Get the Microsoft Corporation KEK 2K CA 2023 certificate.
 
-get_file -L https://go.microsoft.com/fwlink/p/?linkid=2239775 -o $ms/microsoft_corporation_kek_2k_ca_2023.crt
+get_file -L https://go.microsoft.com/fwlink/p/?linkid=2239775 -o $ms/microsoft_corporation_kek_2k_ca_2023.der
 
 # Generate EFI Signature List (ESL) files from the Microsoft certificates
 # using the Microsoft GUID 77fa9abd-0359-4d32-bd60-28f4e78f784b.
 
 sbsiglist_if_changed --type x509 --owner "77fa9abd-0359-4d32-bd60-28f4e78f784b" \
-    $ms/MicCorKEKCA2011_2011-06-24.crt \
+    $ms/MicCorKEKCA2011_2011-06-24.der \
     --output $ms/MicCorKEKCA2011_2011-06-24.esl
 
 sbsiglist_if_changed --type x509 --owner "77fa9abd-0359-4d32-bd60-28f4e78f784b" \
-    $ms/microsoft_corporation_kek_2k_ca_2023.crt \
+    $ms/microsoft_corporation_kek_2k_ca_2023.der \
     --output $ms/microsoft_corporation_kek_2k_ca_2023.esl
 
 # Combine the two ESL keys into one.
 
 [ ! -e $ms/ms_KEK.esl ] && changed="true"
-[ "$changed" == "true" ] &&
+[ "$changed" = "true" ] &&
 cat $ms/{MicCorKEKCA2011_2011-06-24,microsoft_corporation_kek_2k_ca_2023}.esl \
     > $ms/ms_KEK.esl
 
 # Get the Microsoft Windows Production PCA 2011 certificate.
 
 changed=
-get_file -L https://go.microsoft.com/fwlink/p/?linkid=321192 -o $ms/MicWinProPCA2011_2011-10-19.crt
+get_file -L https://go.microsoft.com/fwlink/p/?linkid=321192 -o $ms/MicWinProPCA2011_2011-10-19.der
 
 # Download the Microsoft Windows UEFI CA 2011 certificate for third-party vendors.
 # This is needed by Fedora and, others, presumably.
 
-get_file -L https://go.microsoft.com/fwlink/p/?linkid=321194 -o $ms/MicCorUEFCA2011_2011-06-27.crt
+get_file -L https://go.microsoft.com/fwlink/p/?linkid=321194 -o $ms/MicCorUEFCA2011_2011-06-27.der
 
 # Download the Microsoft Windows UEFI CA 2023 certificate for third-party vendors.
 
-get_file -L https://go.microsoft.com/fwlink/?linkid=2239776 -o $ms/windows_uefi_ca_2023.crt
+get_file -L https://go.microsoft.com/fwlink/?linkid=2239776 -o $ms/windows_uefi_ca_2023.der
 
 # Using the Microsoft GUID 77fa9abd-0359-4d32-bd60-28f4e78f784b, generate EFI Signature List
 # (ESL) files from Microsoft certificates.
 
 sbsiglist_if_changed --type x509 --owner "77fa9abd-0359-4d32-bd60-28f4e78f784b" \
-    $ms/MicWinProPCA2011_2011-10-19.crt \
+    $ms/MicWinProPCA2011_2011-10-19.der \
     --output $ms/MicWinProPCA2011_2011-10-19.esl
 
 sbsiglist_if_changed --type x509 --owner "77fa9abd-0359-4d32-bd60-28f4e78f784b" \
-    $ms/MicCorUEFCA2011_2011-06-27.crt \
+    $ms/MicCorUEFCA2011_2011-06-27.der \
     --output $ms/MicCorUEFCA2011_2011-06-27.esl
 
 sbsiglist_if_changed --type x509 --owner "77fa9abd-0359-4d32-bd60-28f4e78f784b" \
-    $ms/windows_uefi_ca_2023.crt \
+    $ms/windows_uefi_ca_2023.der \
     --output $ms/windows_uefi_ca_2023.esl
 
 # Combine the ESL keys into one.
 
 [ ! -e $ms/ms_db.esl ] && changed="true"
-[ "$changed" == "true" ] &&
+[ "$changed" = "true" ] &&
 cat $ms/{MicWinProPCA2011_2011-10-19,MicCorUEFCA2011_2011-06-27,windows_uefi_ca_2023}.esl \
     > $ms/ms_db.esl
 
